In [2]:
import torch
import torch.nn as nn

In [3]:
vocab = {
    "<PAD>": 0,
    "<UNK>": 1,
    "我": 2,
    "喜欢": 3,
    "机器": 4,
    "学习": 5,
    "AI": 6,
    "深度": 7,
    "有趣": 8
}

vocab_size = len(vocab)

print("词表大小:", vocab_size)

词表大小: 9


In [4]:
sentences = [
    "我 喜欢 机器 学习",
    "我 喜欢 AI",
    "深度 学习 有趣"
]

In [5]:
max_len = 4

encoded_sentences = []

for sentence in sentences:
    tokens = sentence.split()
    ids = [vocab.get(token, vocab["<UNK>"]) for token in tokens]

    while len(ids) < max_len:
        ids.append(vocab["<PAD>"])

    encoded_sentences.append(ids)

print(encoded_sentences)

[[2, 3, 4, 5], [2, 3, 6, 0], [7, 5, 8, 0]]


In [6]:
input_ids = torch.tensor(encoded_sentences)

print(input_ids)
print(input_ids.shape)

tensor([[2, 3, 4, 5],
        [2, 3, 6, 0],
        [7, 5, 8, 0]])
torch.Size([3, 4])


In [7]:
embedding_dim = 5

embedding = nn.Embedding(
    num_embeddings=vocab_size,
    embedding_dim=embedding_dim
)

print(embedding)

Embedding(9, 5)


In [8]:
embedded = embedding(input_ids)

print(embedded)
print(embedded.shape)

tensor([[[ 1.0170,  0.6962, -0.6338,  0.2501, -1.6989],
         [ 1.8180,  0.1561,  0.6363,  0.0051,  1.7349],
         [-1.4515, -1.1955, -0.9369, -1.3498,  0.3771],
         [ 0.7592, -0.4699,  1.6607,  0.9890, -0.7061]],

        [[ 1.0170,  0.6962, -0.6338,  0.2501, -1.6989],
         [ 1.8180,  0.1561,  0.6363,  0.0051,  1.7349],
         [ 0.1312,  0.5022,  0.1106, -0.5423, -1.2993],
         [ 0.4133, -0.1658,  0.9238, -0.2804, -2.0114]],

        [[-0.3777, -1.1587,  0.1991,  2.5070,  1.8473],
         [ 0.7592, -0.4699,  1.6607,  0.9890, -0.7061],
         [ 0.4522,  0.1022, -1.3414, -0.2780, -1.5987],
         [ 0.4133, -0.1658,  0.9238, -0.2804, -2.0114]]],
       grad_fn=<EmbeddingBackward0>)
torch.Size([3, 4, 5])


In [9]:
word_id = torch.tensor([vocab["我"]])

word_embedding = embedding(word_id)

print(word_embedding)

tensor([[ 1.0170,  0.6962, -0.6338,  0.2501, -1.6989]],
       grad_fn=<EmbeddingBackward0>)


In [10]:
sentence = "我 喜欢 AI"

tokens = sentence.split()
ids = [vocab.get(token, vocab["<UNK>"]) for token in tokens]

input_tensor = torch.tensor(ids)

sentence_embedding = embedding(input_tensor)

print(sentence_embedding)
print(sentence_embedding.shape)

tensor([[ 1.0170,  0.6962, -0.6338,  0.2501, -1.6989],
        [ 1.8180,  0.1561,  0.6363,  0.0051,  1.7349],
        [ 0.1312,  0.5022,  0.1106, -0.5423, -1.2993]],
       grad_fn=<EmbeddingBackward0>)
torch.Size([3, 5])
