In [2]:
import torch

x = torch.tensor([1, 2, 3])
print(x)

tensor([1, 2, 3])


In [3]:
import torch

x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

print(x)
print(x.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


In [4]:
x = torch.rand(3, 4)

print(x)
print(x.shape)

tensor([[0.5156, 0.4005, 0.9382, 0.1358],
        [0.2100, 0.5339, 0.6866, 0.9072],
        [0.9092, 0.5271, 0.8309, 0.2510]])
torch.Size([3, 4])


In [5]:
zeros = torch.zeros(2, 3)
ones = torch.ones(2, 3)

print(zeros)
print(ones)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [6]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([10, 20, 30])

print(a + b)
print(b - a)
print(a * b)
print(b / a)

tensor([11, 22, 33])
tensor([ 9, 18, 27])
tensor([10, 40, 90])
tensor([10., 10., 10.])


In [7]:
A = torch.tensor([
    [1, 2],
    [3, 4]
], dtype=torch.float32)

B = torch.tensor([
    [5, 6],
    [7, 8]
], dtype=torch.float32)

C = torch.matmul(A, B)

print(C)

tensor([[19., 22.],
        [43., 50.]])


In [8]:
import numpy as np
import torch

arr = np.array([1, 2, 3])
x = torch.from_numpy(arr)

print(x)
print(type(x))

tensor([1, 2, 3])
<class 'torch.Tensor'>


In [9]:
y = x.numpy()

print(y)
print(type(y))

[1 2 3]
<class 'numpy.ndarray'>
