In [7]:
import torch
import torch.nn as nn
import pandas as pd
X = torch.tensor([
    [1.0, 50.0, 30.0],
    [2.0, 55.0, 40.0],
    [3.0, 60.0, 50.0],
    [4.0, 65.0, 55.0],
    [5.0, 70.0, 65.0],
    [6.0, 75.0, 70.0],
    [7.0, 80.0, 80.0],
    [8.0, 85.0, 85.0],
])
y = torch.tensor([
    [0.0],
    [0.0],
    [0.0],
    [0.0],
    [1.0],
    [1.0],
    [1.0],
    [1.0],
])

In [8]:
df = pd.DataFrame(X.numpy())
print(df)

     0     1     2
0  1.0  50.0  30.0
1  2.0  55.0  40.0
2  3.0  60.0  50.0
3  4.0  65.0  55.0
4  5.0  70.0  65.0
5  6.0  75.0  70.0
6  7.0  80.0  80.0
7  8.0  85.0  85.0


In [9]:
class SimpleNet(nn.Module):
    def __init__(self):
        super().__init__()
        
        self.net = nn.Sequential(
            nn.Linear(3, 4),
            nn.ReLU(),
            nn.Linear(4, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.net(x)

In [10]:
model = SimpleNet()
print(model)

SimpleNet(
  (net): Sequential(
    (0): Linear(in_features=3, out_features=4, bias=True)
    (1): ReLU()
    (2): Linear(in_features=4, out_features=1, bias=True)
    (3): Sigmoid()
  )
)


In [11]:
output = model(X)

print(output)

tensor([[0.0207],
        [0.0216],
        [0.0225],
        [0.0163],
        [0.0170],
        [0.0123],
        [0.0129],
        [0.0093]], grad_fn=<SigmoidBackward0>)


In [12]:
criterion = nn.BCELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.0001)

In [13]:
for epoch in range(1000):
    # 1. 前向传播
    y_pred = model(X)

    # 2. 计算损失
    loss = criterion(y_pred, y)

    # 3. 清空上一次梯度
    optimizer.zero_grad()

    # 4. 反向传播
    loss.backward()

    # 5. 更新参数
    optimizer.step()

    if (epoch + 1) % 100 == 0:
        print(f"第 {epoch+1} 轮，loss = {loss.item():.4f}")

第 100 轮，loss = 0.6033
第 200 轮，loss = 0.5173
第 300 轮，loss = 0.5143
第 400 轮，loss = 0.5114
第 500 轮，loss = 0.5086
第 600 轮，loss = 0.5058
第 700 轮，loss = 0.5031
第 800 轮，loss = 0.5003
第 900 轮，loss = 0.4975
第 1000 轮，loss = 0.4947


In [14]:
with torch.no_grad():
    predictions = model(X)
    predicted_labels = (predictions >= 0.5).float()

print("预测概率：")
print(predictions)

print("预测类别：")
print(predicted_labels)

print("真实标签：")
print(y)

预测概率：
tensor([[0.1794],
        [0.2746],
        [0.3960],
        [0.3922],
        [0.5278],
        [0.5239],
        [0.5624],
        [0.5624]])
预测类别：
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.]])
真实标签：
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.]])
